info:
  contact: {}
paths:
  /userList:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: succeed
      tags:
      - 用户数据
swagger: "2.0"
